# Generated by Django 5.2.8 on 2025-11-30 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verwaltung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kuerzel', models.CharField(blank=True, max_length=50, null=True)),
                ('typ', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vertrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('vertragsnummer', models.CharField(max_length=100)),
                ('rahmenvertrag', models.BooleanField(default=False)),
                ('bezeichnung', models.CharField(blank=True, max_length=255, null=True)),
                ('laufzeit_von', models.DateField(blank=True, null=True)),
                ('laufzeit_bis', models.DateField(blank=True, null=True)),
                ('kuendigungsfrist_tage', models.IntegerField(blank=True, null=True)),
                ('kosten_monat_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kosten_einmalig_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kostenstelle', models.CharField(blank=True, max_length=100, null=True)),
                ('rechnungsempfaenger', models.CharField(blank=True, max_length=255, null=True)),
                ('bemerkung_vertrag', models.TextField(blank=True, null=True)),
                ('verwaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertraege', to='core.verwaltung')),
            ],
            options={
                'ordering': ['provider', 'vertragsnummer'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('verwaltung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.verwaltung')),
            ],
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('standort_code', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_strasse', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_plz', models.CharField(blank=True, max_length=10, null=True)),
                ('adresse_ort', models.CharField(blank=True, max_length=100, null=True)),
                ('gebaeude_typ', models.CharField(blank=True, max_length=50, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('verwaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standorte', to='core.verwaltung')),
            ],
            options={
                'ordering': ['verwaltung__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WanLeitung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('anschlussart', models.CharField(blank=True, max_length=100, null=True)),
                ('bandbreite_down_mbit', models.IntegerField(blank=True, null=True)),
                ('bandbreite_up_mbit', models.IntegerField(blank=True, null=True)),
                ('medium', models.CharField(blank=True, max_length=50, null=True)),
                ('vlan_id', models.IntegerField(blank=True, null=True)),
                ('ip_adressbereich', models.CharField(blank=True, max_length=50, null=True)),
                ('nat_aktiv', models.BooleanField(default=False)),
                ('cpe_geraet', models.CharField(blank=True, max_length=255, null=True)),
                ('cpe_management_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('in_kuendigung', 'In Kündigung'), ('geplant', 'Geplant'), ('ausser_betrieb', 'Außer Betrieb')], default='aktiv', max_length=50)),
                ('inbetriebnahme_datum', models.DateField(blank=True, null=True)),
                ('ausserbetriebnahme_datum', models.DateField(blank=True, null=True)),
                ('bemerkung_technik', models.TextField(blank=True, null=True)),
                ('backup_leitung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.wanleitung')),
                ('standort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitungen', to='core.standort')),
                ('vertrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leitungen', to='core.vertrag')),
            ],
            options={
                'ordering': ['standort__verwaltung__name', 'standort__name', 'provider'],
            },
        ),
    ]
