# Generated by Django 5.2.8 on 2025-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanleitung',
            name='bezeichnung',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verwaltung',
            name='typ',
            field=models.CharField(blank=True, choices=[('kreisverwaltung', 'Kreisverwaltung'), ('amtsverwaltung', 'Amtsverwaltung'), ('stadtverwaltung', 'Stadtverwaltung'), ('gemeindeverwaltung', 'Gemeindeverwaltung')], max_length=50, null=True),
        ),
    ]
