# Generated by Django 5.2.8 on 2026-02-16 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_wanleitung_bezeichnung_alter_verwaltung_typ"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WanBeauftragung",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titel", models.CharField(max_length=255)),
                ("ticket_nummer", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "prioritaet",
                    models.CharField(
                        choices=[
                            ("niedrig", "Niedrig"),
                            ("normal", "Normal"),
                            ("hoch", "Hoch"),
                            ("kritisch", "Kritisch"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("in_pruefung", "In Pruefung"),
                            ("beauftragt", "Beauftragt"),
                            ("umgesetzt", "Umgesetzt"),
                            ("abgelehnt", "Abgelehnt"),
                            ("storniert", "Storniert"),
                        ],
                        default="offen",
                        max_length=20,
                    ),
                ),
                ("bedarf_down_mbit", models.PositiveIntegerField(blank=True, null=True, verbose_name="Bedarf Downlink (Mbit/s)")),
                ("bedarf_up_mbit", models.PositiveIntegerField(blank=True, null=True, verbose_name="Bedarf Uplink (Mbit/s)")),
                ("umsetzung_bis", models.DateField(blank=True, null=True)),
                ("angefragt_am", models.DateField(auto_now_add=True)),
                ("kostenrahmen_monat_netto", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("kostenrahmen_einmalig_netto", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("begruendung", models.TextField(blank=True, null=True)),
                ("bemerkung", models.TextField(blank=True, null=True)),
                (
                    "bestehende_leitung",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="beauftragungen", to="core.wanleitung"),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "standort",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="beauftragungen", to="core.standort"),
                ),
            ],
            options={
                "ordering": ["-angefragt_am", "-id"],
            },
        ),
    ]
