# Generated by Django 5.2.8 on 2026-02-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_wanbeauftragung"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS `core_provider` (
                            `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                            `name` varchar(255) NOT NULL,
                            `kuerzel` varchar(50) NULL,
                            `kundennummer` varchar(100) NULL,
                            `kontakt_name` varchar(255) NULL,
                            `kontakt_mail` varchar(254) NULL,
                            `kontakt_tel` varchar(50) NULL,
                            `bemerkung` longtext NULL
                        ) ENGINE=InnoDB
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Provider",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=255)),
                        ("kuerzel", models.CharField(blank=True, max_length=50, null=True)),
                        ("kundennummer", models.CharField(blank=True, max_length=100, null=True)),
                        ("kontakt_name", models.CharField(blank=True, max_length=255, null=True)),
                        ("kontakt_mail", models.EmailField(blank=True, max_length=254, null=True)),
                        ("kontakt_tel", models.CharField(blank=True, max_length=50, null=True)),
                        ("bemerkung", models.TextField(blank=True, null=True)),
                    ],
                    options={"ordering": ["name"]},
                ),
            ],
        ),
        migrations.AddField(
            model_name="wanbeauftragung",
            name="angefragte_provider",
            field=models.ManyToManyField(blank=True, related_name="beauftragungen", to="core.provider"),
        ),
        migrations.AddField(
            model_name="wanbeauftragung",
            name="anfrage_template_betreff",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wanbeauftragung",
            name="anfrage_template_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
