# Generated by Django 5.2.8 on 2026-02-16 15:06

import django.db.models.deletion
from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        table_description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return any(col.name == column_name for col in table_description)


def _add_standort_arbeitsplaetze_if_missing(apps, schema_editor):
    model = apps.get_model('core', 'Standort')
    if _column_exists(schema_editor, model._meta.db_table, 'arbeitsplaetze'):
        return

    field = models.PositiveIntegerField(default=0, verbose_name='Arbeitsplätze')
    field.set_attributes_from_name('arbeitsplaetze')
    schema_editor.add_field(model, field)


def _add_vertrag_provider_ref_if_missing(apps, schema_editor):
    model = apps.get_model('core', 'Vertrag')
    if _column_exists(schema_editor, model._meta.db_table, 'provider_ref_id'):
        return

    field = models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name='vertraege',
        to='core.provider',
    )
    field.set_attributes_from_name('provider_ref')
    schema_editor.add_field(model, field)


def _add_wanleitung_provider_ref_if_missing(apps, schema_editor):
    model = apps.get_model('core', 'WanLeitung')
    if _column_exists(schema_editor, model._meta.db_table, 'provider_ref_id'):
        return

    field = models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name='leitungen',
        to='core.provider',
    )
    field.set_attributes_from_name('provider_ref')
    schema_editor.add_field(model, field)


def _unique_constraint_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)

    for constraint in constraints.values():
        if constraint.get('unique') and constraint.get('columns') == [column_name]:
            return True
    return False


def _ensure_verwaltung_kuerzel_unique_if_missing(apps, schema_editor):
    model = apps.get_model('core', 'Verwaltung')
    if _unique_constraint_exists(schema_editor, model._meta.db_table, 'kuerzel'):
        return

    field = model._meta.get_field('kuerzel').clone()
    field.unique = True
    sql = schema_editor._create_unique_sql(model, [field])
    if sql:
        schema_editor.execute(sql)


def _run_ensure_verwaltung_kuerzel_unique(apps, schema_editor):
    func = globals().get('_ensure_verwaltung_kuerzel_unique_if_missing')
    if callable(func):
        return func(apps, schema_editor)
    return None


def _add_wanleitung_tarif_ref_if_missing(apps, schema_editor):
    model = apps.get_model('core', 'WanLeitung')
    if _column_exists(schema_editor, model._meta.db_table, 'tarif_ref_id'):
        return

    field = models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name='leitungen',
        to='core.tarif',
    )
    field.set_attributes_from_name('tarif_ref')
    schema_editor.add_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wanbeauftragung_anfrage_template_and_provider'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS `core_provider` (
                    `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                    `name` varchar(255) NOT NULL,
                    `kuerzel` varchar(50) NULL,
                    `kundennummer` varchar(100) NULL,
                    `kontakt_name` varchar(255) NULL,
                    `kontakt_mail` varchar(254) NULL,
                    `kontakt_tel` varchar(50) NULL,
                    `bemerkung` longtext NULL
                ) ENGINE=InnoDB
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS `core_globalsettings` (
                            `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                            `mbit_pro_arbeitsplatz` integer UNSIGNED NOT NULL DEFAULT 10
                        ) ENGINE=InnoDB
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='GlobalSettings',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('mbit_pro_arbeitsplatz', models.PositiveIntegerField(default=10, verbose_name='Mbit/s pro Arbeitsplatz')),
                    ],
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='standort',
            options={'ordering': ['standort_code']},
        ),
        migrations.AlterModelOptions(
            name='verwaltung',
            options={'ordering': ['kuerzel']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_standort_arbeitsplaetze_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='standort',
                    name='arbeitsplaetze',
                    field=models.PositiveIntegerField(default=0, verbose_name='Arbeitsplätze'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_vertrag_provider_ref_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='vertrag',
                    name='provider_ref',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertraege', to='core.provider'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_wanleitung_provider_ref_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='wanleitung',
                    name='provider_ref',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leitungen', to='core.provider'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='standort',
            name='adresse_ort',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='standort',
            name='adresse_plz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postleitzahl'),
        ),
        migrations.AlterField(
            model_name='standort',
            name='adresse_strasse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='vertrag',
            name='bemerkung_vertrag',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkung Vertrag'),
        ),
        migrations.AlterField(
            model_name='vertrag',
            name='rechnungsempfaenger',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rechnungsempfänger'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_run_ensure_verwaltung_kuerzel_unique, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='verwaltung',
                    name='kuerzel',
                    field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='VKZ'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='wanleitung',
            name='ausserbetriebnahme_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Außerbetriebnahme-Datum'),
        ),
        migrations.AlterField(
            model_name='wanleitung',
            name='bemerkung_technik',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkung Technik'),
        ),
        migrations.AlterField(
            model_name='wanleitung',
            name='cpe_geraet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CPE Gerät'),
        ),
        migrations.AlterField(
            model_name='wanleitung',
            name='cpe_management_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPE Management IP'),
        ),
        migrations.AlterField(
            model_name='wanleitung',
            name='inbetriebnahme_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Inbetriebnahme-Datum'),
        ),
        migrations.AlterField(
            model_name='wanleitung',
            name='ip_adressbereich',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP-Adresse(n)'),
        ),
        migrations.AlterField(
            model_name='wanleitung',
            name='medium',
            field=models.CharField(choices=[('dsl', 'DSL'), ('fibre', 'Glasfaser'), ('mobile', 'Mobilfunk'), ('cable', 'Kabel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wanleitung',
            name='nat_aktiv',
            field=models.BooleanField(default=False, verbose_name='NAT Aktiv?'),
        ),
        migrations.AlterField(
            model_name='wanleitung',
            name='vlan_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='VLAN-ID'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS `core_tarif` (
                            `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                            `name` varchar(255) NOT NULL,
                            `beschreibung` longtext NULL,
                            `bandbreite_down_mbit` integer NULL,
                            `bandbreite_up_mbit` integer NULL,
                            `medium` varchar(50) NULL,
                            `bemerkung` longtext NULL,
                            `provider_id` bigint NOT NULL,
                            CONSTRAINT `core_tarif_provider_id_fk` FOREIGN KEY (`provider_id`) REFERENCES `core_provider` (`id`)
                        ) ENGINE=InnoDB
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Tarif',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('beschreibung', models.TextField(blank=True, null=True)),
                        ('bandbreite_down_mbit', models.IntegerField(blank=True, null=True)),
                        ('bandbreite_up_mbit', models.IntegerField(blank=True, null=True)),
                        ('medium', models.CharField(blank=True, max_length=50, null=True)),
                        ('bemerkung', models.TextField(blank=True, null=True)),
                        ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarife', to='core.provider')),
                    ],
                    options={
                        'ordering': ['provider__name', 'name'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_wanleitung_tarif_ref_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='wanleitung',
                    name='tarif_ref',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leitungen', to='core.tarif'),
                ),
            ],
        ),
    ]
