# Generated by Django 5.2.8 on 2026-02-16 17:10

from django.db import migrations, models


def forward_copy_template(apps, schema_editor):
    GlobalSettings = apps.get_model("core", "GlobalSettings")
    WanBeauftragung = apps.get_model("core", "WanBeauftragung")

    settings_obj, _ = GlobalSettings.objects.get_or_create(pk=1, defaults={"mbit_pro_arbeitsplatz": 10})
    if settings_obj.anfrage_template_text:
        return

    source = (
        WanBeauftragung.objects.exclude(anfrage_template_text__isnull=True)
        .exclude(anfrage_template_text__exact="")
        .order_by("id")
        .first()
    )
    if source:
        settings_obj.anfrage_template_text = source.anfrage_template_text
        settings_obj.save(update_fields=["anfrage_template_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_globalsettings_alter_standort_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="anfrage_template_text",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Platzhalter: {anbieter_name}, {anbieter_kuerzel}, {standort_name}, {standort_code}, "
                    "{verwaltung_name}, {bedarf_down_mbit}, {bedarf_up_mbit}, {umsetzung_bis}, {titel}, {ticket_nummer}"
                ),
                null=True,
                verbose_name="WAN-Anfrage Template (Text)",
            ),
        ),
        migrations.RunPython(forward_copy_template, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="wanbeauftragung",
            name="anfrage_template_betreff",
        ),
        migrations.RemoveField(
            model_name="wanbeauftragung",
            name="anfrage_template_text",
        ),
    ]
