# Generated by Django 5.2.8 on 2026-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_global_template_for_wan_anfragen"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="anfrage_template_text",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Platzhalter: {anbieter_name}, {anbieter_kuerzel}, {standort_name}, {standort_code}, "
                    "{verwaltung_name}, {bedarf_down_mbit}, {bedarf_up_mbit}, {umsetzung_bis}, {titel}, {ticket_nummer}"
                ),
                null=True,
                verbose_name="Anfrage-Template (Text)",
            ),
        ),
    ]
