# Generated by Django 5.2.8 on 2026-02-16 17:50

import django.db.models.deletion
from django.db import migrations, models


def create_existing_kontexte(apps, schema_editor):
    WanBeauftragung = apps.get_model("core", "WanBeauftragung")
    WanBeauftragungProviderKontext = apps.get_model("core", "WanBeauftragungProviderKontext")

    through = WanBeauftragung.angefragte_provider.through
    for rel in through.objects.all():
        WanBeauftragungProviderKontext.objects.get_or_create(
            beauftragung_id=rel.wanbeauftragung_id,
            provider_id=rel.provider_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_provider_anfrage_template_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderZusatzoption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("beschreibung", models.TextField(blank=True, null=True)),
                ("kosten_monat_netto", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("kosten_einmalig_netto", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("aktiv", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="zusatzoptionen", to="core.provider"),
                ),
            ],
            options={"ordering": ["provider__name", "name"]},
        ),
        migrations.CreateModel(
            name="WanBeauftragungProviderKontext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template_override_text", models.TextField(blank=True, null=True)),
                ("anfrage_notiz", models.TextField(blank=True, null=True)),
                (
                    "beauftragung",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="provider_kontexte", to="core.wanbeauftragung"),
                ),
                (
                    "provider",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="beauftragungs_kontexte", to="core.provider"),
                ),
                (
                    "tarif",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beauftragungs_kontexte",
                        to="core.tarif",
                    ),
                ),
                (
                    "zusatzoptionen",
                    models.ManyToManyField(blank=True, related_name="beauftragungs_kontexte", to="core.providerzusatzoption"),
                ),
            ],
            options={"ordering": ["provider__name"], "unique_together": {("beauftragung", "provider")}},
        ),
        migrations.RunPython(create_existing_kontexte, migrations.RunPython.noop),
    ]
