# Generated by Django 5.2.8 on 2026-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_provider_optionen_und_beauftragungs_kontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='anfrage_template_text',
            field=models.TextField(blank=True, help_text='Platzhalter: {anbieter_name}, {anbieter_kuerzel}, {standort_name}, {standort_code}, {standort_adresse_komplett}, {verwaltung_name}, {bedarf_down_mbit}, {bedarf_up_mbit}, {umsetzung_bis}, {titel}, {ticket_nummer}', null=True, verbose_name='WAN-Anfrage Template (Text)'),
        ),
    ]
