# Generated by Django 5.2.8 on 2026-02-22 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_alter_globalsettings_anfrage_template_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('model_label', models.CharField(max_length=120)),
                ('object_repr', models.CharField(max_length=255)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DokumentAnhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255)),
                ('datei', models.FileField(upload_to='anhaenge/%Y/%m/')),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-hochgeladen_am'],
            },
        ),
        migrations.CreateModel(
            name='Erinnerung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('typ', models.CharField(choices=[('vertrag', 'Vertrag'), ('beauftragung', 'Beauftragung')], max_length=20)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('erledigt', 'Erledigt'), ('ueberfaellig', 'Überfällig')], default='offen', max_length=20)),
                ('faellig_am', models.DateField()),
                ('notiz', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', 'faellig_am', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='provider',
            name='kontakt_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kontakt E-Mail'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='kontakt_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontakt Name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='kontakt_tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kontakt Telefon'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='kuerzel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kürzel'),
        ),
        migrations.AlterField(
            model_name='providerzusatzoption',
            name='kosten_einmalig_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kosten einmalig (Netto)'),
        ),
        migrations.AlterField(
            model_name='providerzusatzoption',
            name='kosten_monat_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kosten p. Monat (Netto)'),
        ),
        migrations.AddConstraint(
            model_name='providerzusatzoption',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='uniq_option_name_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='standort',
            constraint=models.UniqueConstraint(condition=models.Q(('standort_code__isnull', True), _negated=True), fields=('standort_code',), name='uniq_standort_code_not_null'),
        ),
        migrations.AddConstraint(
            model_name='tarif',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='uniq_tarif_name_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='vertrag',
            constraint=models.CheckConstraint(condition=models.Q(('laufzeit_von__isnull', True), ('laufzeit_bis__isnull', True), ('laufzeit_bis__gte', models.F('laufzeit_von')), _connector='OR'), name='vertrag_laufzeit_von_bis_valid'),
        ),
        migrations.AddConstraint(
            model_name='vertrag',
            constraint=models.CheckConstraint(condition=models.Q(('kuendigungsfrist_tage__isnull', True), ('kuendigungsfrist_tage__gte', 0), _connector='OR'), name='vertrag_kuendigungsfrist_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wanbeauftragung',
            constraint=models.CheckConstraint(condition=models.Q(('umsetzung_bis__isnull', True), ('angefragt_am__isnull', True), ('umsetzung_bis__gte', models.F('angefragt_am')), _connector='OR'), name='beauftragung_umsetzung_after_anfrage'),
        ),
        migrations.AddConstraint(
            model_name='wanleitung',
            constraint=models.CheckConstraint(condition=models.Q(('vlan_id__isnull', True), models.Q(('vlan_id__gte', 1), ('vlan_id__lte', 4094)), _connector='OR'), name='wanleitung_vlan_in_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='wanleitung',
            constraint=models.CheckConstraint(condition=models.Q(('inbetriebnahme_datum__isnull', True), ('ausserbetriebnahme_datum__isnull', True), ('ausserbetriebnahme_datum__gte', models.F('inbetriebnahme_datum')), _connector='OR'), name='wanleitung_ausserbetriebnahme_after_inbetriebnahme'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='dokumentanhang',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='dokumentanhang',
            name='hochgeladen_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erinnerung',
            name='beauftragung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erinnerungen', to='core.wanbeauftragung'),
        ),
        migrations.AddField(
            model_name='erinnerung',
            name='vertrag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erinnerungen', to='core.vertrag'),
        ),
        migrations.AddField(
            model_name='erinnerung',
            name='zugewiesen_an',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='erinnerung',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('vertrag__isnull', False), ('beauftragung__isnull', True), ('typ', 'vertrag')), models.Q(('vertrag__isnull', True), ('beauftragung__isnull', False), ('typ', 'beauftragung')), _connector='OR'), name='erinnerung_exactly_one_target'),
        ),
    ]
