# Generated by Django 5.2.8 on 2026-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auditlog_dokumentanhang_erinnerung_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='standort',
            name='uniq_standort_code_not_null',
        ),
        migrations.AddConstraint(
            model_name='standort',
            constraint=models.UniqueConstraint(condition=models.Q(('standort_code__isnull', False), models.Q(('standort_code', ''), _negated=True)), fields=('standort_code',), name='uniq_standort_code_not_blank'),
        ),
    ]
