# Generated by Django 5.2.8 on 2026-02-22 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_remove_standort_uniq_standort_code_not_null_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wanbeauftragungproviderkontext',
            name='anfrage_gesendet_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wanbeauftragungproviderkontext',
            name='anfrage_gesendet_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_anfragen_gesendet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wanbeauftragungproviderkontext',
            name='angebot_kosten_einmalig_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wanbeauftragungproviderkontext',
            name='angebot_kosten_monat_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wanbeauftragungproviderkontext',
            name='angebot_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Subjektive Bewertung 0.0 bis 10.0', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='wanbeauftragungproviderkontext',
            name='angebot_umsetzungstage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wanbeauftragungproviderkontext',
            name='empfohlen',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ObjektNotiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-erstellt_am', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('nachricht', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('gelesen', models.BooleanField(default=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['gelesen', '-erstellt_am', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('erinnerung', 'Erinnerungen'), ('beauftragung', 'Beauftragungen'), ('standort', 'Standorte')], max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('querystring', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target', 'name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'target', 'name'), name='uniq_filter_name_per_target')],
            },
        ),
    ]
