# Generated by Django 5.2.8 on 2026-02-22 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_wanbeauftragungproviderkontext_anfrage_gesendet_am_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='ticket_header_name',
            field=models.CharField(default='X-Ticket-Nummer', max_length=100, verbose_name='Headername Ticketnummer'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ticket_system_email',
            field=models.EmailField(blank=True, help_text='An diese Adresse wird nach Genehmigung automatisch gesendet.', max_length=254, null=True, verbose_name='Ticketsystem E-Mail'),
        ),
        migrations.AddField(
            model_name='wanbeauftragung',
            name='genehmigt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wanbeauftragung',
            name='genehmigt_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wanbeauftragung',
            name='genehmigt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genehmigte_beauftragungen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wanbeauftragung',
            name='genehmigungs_notiz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wanbeauftragung',
            name='ticket_gesendet_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
