# Generated by Django 5.2.8 on 2026-03-07 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0014_globalsettings_ticket_header_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentMappe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('freigegeben', 'Freigegeben'), ('archiviert', 'Archiviert')], default='entwurf', max_length=20)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokument_mappen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-erstellt_am', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderBewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('preis_score', models.PositiveSmallIntegerField(default=5)),
                ('umsetzung_score', models.PositiveSmallIntegerField(default=5)),
                ('sla_score', models.PositiveSmallIntegerField(default=5)),
                ('support_score', models.PositiveSmallIntegerField(default=5)),
                ('qualitaet_score', models.PositiveSmallIntegerField(default=5)),
                ('gesamt_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('beauftragung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_bewertungen', to='core.wanbeauftragung')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_bewertungen', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to='core.provider')),
            ],
            options={
                'ordering': ['-erstellt_am', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DokumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('datei', models.FileField(upload_to='dokument_versionen/%Y/%m/')),
                ('changelog', models.TextField(blank=True, null=True)),
                ('freigegeben', models.BooleanField(default=False)),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokument_versionen', to=settings.AUTH_USER_MODEL)),
                ('mappe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versionen', to='core.dokumentmappe')),
            ],
            options={
                'ordering': ['-version', '-id'],
                'constraints': [models.UniqueConstraint(fields=('mappe', 'version'), name='uniq_dokument_version_per_mappe')],
            },
        ),
        migrations.CreateModel(
            name='LeitungsStoerung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('behoben', 'Behoben')], default='offen', max_length=30)),
                ('impact', models.CharField(choices=[('niedrig', 'Niedrig'), ('mittel', 'Mittel'), ('hoch', 'Hoch'), ('kritisch', 'Kritisch')], default='mittel', max_length=20)),
                ('ticket_nummer', models.CharField(blank=True, max_length=100, null=True)),
                ('geoeffnet_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('erwartet_behebung_bis', models.DateTimeField(blank=True, null=True)),
                ('behoben_am', models.DateTimeField(blank=True, null=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stoerungen_erstellt', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stoerungen', to='core.provider')),
                ('wanleitung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoerungen', to='core.wanleitung')),
            ],
            options={
                'ordering': ['status', '-geoeffnet_am', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('behoben_am__isnull', True), ('geoeffnet_am__isnull', True), ('behoben_am__gte', models.F('geoeffnet_am')), _connector='OR'), name='stoerung_behoben_after_opened')],
            },
        ),
        migrations.CreateModel(
            name='ObjektBerechtigung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Anzeigen'), ('edit', 'Bearbeiten'), ('approve', 'Genehmigen'), ('export', 'Exportieren'), ('docs', 'Dokumente verwalten')], max_length=20)),
                ('erlaubt', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objekt_berechtigungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'action', 'content_type_id', 'object_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'action', 'content_type', 'object_id'), name='uniq_objekt_berechtigung_per_action')],
            },
        ),
    ]
