# Generated by Django 5.2.15 on 2026-07-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_dokumentmappe_providerbewertung_dokumentversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeauftragungApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reihenfolge", models.PositiveSmallIntegerField(default=1)),
                ("rolle", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("freigegeben", "Freigegeben"),
                            ("abgelehnt", "Abgelehnt"),
                        ],
                        default="offen",
                        max_length=20,
                    ),
                ),
                ("notiz", models.TextField(blank=True, null=True)),
                ("entschieden_am", models.DateTimeField(blank=True, null=True)),
                (
                    "beauftragung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_steps",
                        to="core.wanbeauftragung",
                    ),
                ),
                (
                    "genehmiger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["beauftragung", "reihenfolge", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("beauftragung", "reihenfolge"),
                        name="uniq_approval_step_order_per_beauftragung",
                    )
                ],
            },
        ),
    ]
